# to enable/disable failing of this project set these values...
env:
  # Crashing configuration

  # if enabled the process crashes
  CRASH: true

  # the period of time before the process crashes if crash is enabled.
  # Uses https://golang.org/pkg/time/#ParseDuration
  CRASH_DURATION: 10s

  # Http request failing
  # set to 0 for no request failing, 1 for every request, N for the nth request to fail
  REQUEST_FAIL: 0

  # the HTTP request failure code if failing a request
  REQUEST_ERROR_CODE: 404


# other k8s settings
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []

  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

# HorizontalPodAutoscaler
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  cpuTargetAverageUtilization: 80
  memoryTargetAverageUtilization: 80

# Canary deployments
# If enabled, Istio and Flagger need to be installed in the cluster
canary:
  enabled: false
  progressDeadlineSeconds: 60
  analysis:
    interval: "1m"
    threshold: 5
    maxWeight: 60
    stepWeight: 20
    # WARNING: Canary deployments will fail and rollback if there is no traffic that will generate the below specified metrics.
    metrics:
      latency:
        threshold: 500
        interval: "1m"
  # The host is using Istio Gateway or the underlying ingress mechanism
  # This value is defaulted from the environments jx-requirements.yml ingress configuration
  host: ""

service:
  name: go-chaos
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations: {}
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: ""
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: ""

# custom ingress annotations on this service
ingress:
  annotations: {}
  # defaults to nginx if no other ingress class annotation specified
  classAnnotation: ""

serviceAccount:
  enabled: true
  name: ""
  annotations: {}
#    iam.gke.io/gcp-service-account: my-sa-in-gke
  labels: {}
#    my-custom-label: value

# values we use from the `jx-requirements.yml` file if we are using helmfile and helm 3
jxRequirements:
  ingress:
    # shared ingress annotations on all services
    annotations: {}
    #  kubernetes.io/ingress.class: nginx

    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "extensions/v1beta1"

    # the domain for hosts
    domain: ""
    externalDNS: false
    namespaceSubDomain: -jx.
    serviceType: ""
    tls:
      email: ""
      enabled: false
      production: false
      secretName: ""


